/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Enum.java to edit this template
 */
package lexico;

/**
 *
 * @author Froylan Lara Oses
 */
public enum Tokens {
    IDENTIFICADOR,
    ENDLINE,
    SEPARADOR,
    SIGNOIGUAL,
    DOSPUNTOS,
    COMA,
    LITINT,LITFLOAT,LITTRUE,LITFALSE,
    LITCHAR,LITSTRING,TIPOINT,TIPOFlOAT,TIPOBOOL,TIPOCHAR,TIPOSTRING,SIGRESTA,SIGSUMA,SIGMULTIPLICACION,
    SIGDIVISION,SIGMODULO,SIGPOTENCIA,CONGUNCION,DISYUNSION,NEGACION,AUMENTAR,DISMINUIR,MENOR,MENORIGUAL,MAYOR,
    MAYORIGUAL,IGUAL,DIFERENTE,ABREPARENTESIS,CIERRAPARENTESIS,ABRELLAVE,CIERRALLAVE,RESERVREAD,RESERVWRITE,RESERVIF,RESERVELSE,
    RESERVSWITCH,RESERVWHILE,RESERVFORRANGE,RESERVMAIN,RESERVBREAK,RESERVRETURN,RESERVCASE,RESERVDEFAULT,ERROR,COMENTARIO,COMENTARIOBLOQUE,SALTOLINEA
}
