/* The following code was generated by JFlex 1.4.3 on 11/26/23, 3:37 PM */

package sintaxis;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 11/26/23, 3:37 PM from the specification file
 * <tt>../Analizador/src/sintaxis/LexerCup</tt>
 */
class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\12\0\1\60\2\0\1\61\22\0\1\61\1\16\1\0\1\4\1\0"+
    "\1\12\1\14\1\56\1\21\1\22\1\2\1\11\1\7\1\10\1\53"+
    "\1\1\1\52\11\51\1\6\1\3\1\17\1\5\1\20\2\0\21\54"+
    "\1\42\10\54\1\0\1\57\1\0\1\13\1\55\1\0\1\27\1\46"+
    "\1\37\1\30\1\26\1\34\1\44\1\40\1\32\1\54\1\47\1\35"+
    "\1\45\1\43\1\41\2\54\1\25\1\36\1\33\1\50\1\54\1\31"+
    "\3\54\1\23\1\15\1\24\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\14\26\2\27"+
    "\1\1\1\30\2\0\1\31\1\32\1\0\1\33\1\34"+
    "\1\35\1\36\5\26\1\37\14\26\3\0\1\40\1\0"+
    "\6\26\1\41\13\26\1\42\1\43\1\44\1\45\1\26"+
    "\1\46\3\26\1\47\5\26\1\50\1\51\1\52\1\26"+
    "\1\53\2\26\1\54\1\55\1\56\1\57\3\26\1\60"+
    "\1\61\2\26\1\62\1\63\1\64\1\26\1\65";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\62\0\62\0\62\0\226\0\62"+
    "\0\62\0\310\0\372\0\62\0\62\0\62\0\62\0\u012c"+
    "\0\u015e\0\u0190\0\62\0\62\0\62\0\62\0\u01c2\0\u01f4"+
    "\0\u0226\0\u0258\0\u028a\0\u02bc\0\u02ee\0\u0320\0\u0352\0\u0384"+
    "\0\u03b6\0\u03e8\0\u041a\0\u044c\0\u047e\0\u04b0\0\u04e2\0\u0514"+
    "\0\62\0\62\0\u044c\0\62\0\62\0\62\0\62\0\u0546"+
    "\0\u0578\0\u05aa\0\u05dc\0\u060e\0\u0226\0\u0640\0\u0672\0\u06a4"+
    "\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802\0\u0834"+
    "\0\u0866\0\u0898\0\u08ca\0\u08fc\0\62\0\u092e\0\u0960\0\u0992"+
    "\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0226\0\u0a8c\0\u0abe\0\u0af0"+
    "\0\u0b22\0\u0b54\0\u0b86\0\u0bb8\0\u0bea\0\u0c1c\0\u0c4e\0\u0c80"+
    "\0\u0cb2\0\62\0\62\0\u0226\0\u0ce4\0\u0226\0\u0d16\0\u0d48"+
    "\0\u0d7a\0\u0226\0\u0dac\0\u0dde\0\u0e10\0\u0e42\0\u0e74\0\u0226"+
    "\0\u0226\0\u0226\0\u0ea6\0\u0226\0\u0ed8\0\u0f0a\0\u0226\0\u0226"+
    "\0\u0226\0\u0226\0\u0f3c\0\u0f6e\0\u0fa0\0\u0226\0\u0226\0\u0fd2"+
    "\0\u1004\0\u0226\0\u0226\0\u0226\0\u1036\0\u0226";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\35\1\36\1\31\1\37\1\40"+
    "\5\31\1\41\1\42\2\31\1\43\1\44\1\2\1\31"+
    "\1\2\1\45\1\2\2\46\63\0\1\47\1\50\64\0"+
    "\1\51\64\0\1\52\40\0\1\43\1\53\20\0\1\54"+
    "\55\0\1\55\61\0\1\56\61\0\1\57\101\0\1\31"+
    "\1\60\24\31\1\0\2\31\31\0\10\31\1\61\15\31"+
    "\1\0\2\31\31\0\26\31\1\0\2\31\31\0\1\31"+
    "\1\62\24\31\1\0\2\31\31\0\1\63\12\31\1\64"+
    "\12\31\1\0\2\31\31\0\7\31\1\65\6\31\1\66"+
    "\7\31\1\0\2\31\31\0\1\67\25\31\1\0\2\31"+
    "\31\0\2\31\1\70\5\31\1\71\3\31\1\72\11\31"+
    "\1\0\2\31\31\0\4\31\1\73\1\31\1\74\17\31"+
    "\1\0\2\31\31\0\2\31\1\75\10\31\1\76\12\31"+
    "\1\0\2\31\31\0\2\31\1\77\23\31\1\0\2\31"+
    "\31\0\1\100\13\31\1\101\11\31\1\0\2\31\55\0"+
    "\2\43\1\102\61\0\1\102\6\0\56\103\1\0\1\104"+
    "\2\103\60\0\2\46\60\47\1\105\1\47\2\50\1\106"+
    "\57\50\25\0\2\31\1\107\3\31\1\110\17\31\1\0"+
    "\2\31\31\0\11\31\1\111\14\31\1\0\2\31\31\0"+
    "\7\31\1\112\16\31\1\0\2\31\31\0\5\31\1\113"+
    "\20\31\1\0\2\31\31\0\5\31\1\114\20\31\1\0"+
    "\2\31\31\0\6\31\1\115\17\31\1\0\2\31\31\0"+
    "\23\31\1\116\2\31\1\0\2\31\31\0\10\31\1\117"+
    "\15\31\1\0\2\31\31\0\14\31\1\120\11\31\1\0"+
    "\2\31\31\0\1\121\25\31\1\0\2\31\31\0\5\31"+
    "\1\122\20\31\1\0\2\31\31\0\1\123\25\31\1\0"+
    "\2\31\31\0\11\31\1\124\14\31\1\0\2\31\31\0"+
    "\2\31\1\125\23\31\1\0\2\31\31\0\5\31\1\126"+
    "\20\31\1\0\2\31\31\0\1\31\1\127\24\31\1\0"+
    "\2\31\31\0\14\31\1\130\11\31\1\0\2\31\55\0"+
    "\2\131\65\0\1\132\3\0\60\103\1\0\1\103\1\50"+
    "\1\133\1\106\57\50\25\0\3\31\1\134\22\31\1\0"+
    "\2\31\31\0\23\31\1\135\2\31\1\0\2\31\31\0"+
    "\1\31\1\136\24\31\1\0\2\31\31\0\2\31\1\137"+
    "\23\31\1\0\2\31\31\0\6\31\1\140\17\31\1\0"+
    "\2\31\31\0\10\31\1\141\15\31\1\0\2\31\31\0"+
    "\1\31\1\142\24\31\1\0\2\31\31\0\11\31\1\143"+
    "\14\31\1\0\2\31\31\0\2\31\1\144\23\31\1\0"+
    "\2\31\31\0\15\31\1\145\10\31\1\0\2\31\31\0"+
    "\6\31\1\146\17\31\1\0\2\31\31\0\5\31\1\147"+
    "\20\31\1\0\2\31\31\0\1\31\1\150\24\31\1\0"+
    "\2\31\31\0\1\151\25\31\1\0\2\31\31\0\16\31"+
    "\1\152\7\31\1\0\2\31\31\0\2\31\1\153\23\31"+
    "\1\0\2\31\31\0\10\31\1\154\15\31\1\0\2\31"+
    "\55\0\1\131\35\0\1\155\25\31\1\0\2\31\31\0"+
    "\23\31\1\156\2\31\1\0\2\31\31\0\1\31\1\157"+
    "\24\31\1\0\2\31\31\0\1\31\1\160\24\31\1\0"+
    "\2\31\31\0\1\31\1\161\24\31\1\0\2\31\31\0"+
    "\6\31\1\162\17\31\1\0\2\31\31\0\2\31\1\163"+
    "\23\31\1\0\2\31\31\0\12\31\1\164\13\31\1\0"+
    "\2\31\31\0\16\31\1\165\7\31\1\0\2\31\31\0"+
    "\22\31\1\166\3\31\1\0\2\31\31\0\16\31\1\167"+
    "\7\31\1\0\2\31\31\0\10\31\1\170\15\31\1\0"+
    "\2\31\31\0\16\31\1\171\7\31\1\0\2\31\31\0"+
    "\13\31\1\172\12\31\1\0\2\31\31\0\17\31\1\173"+
    "\6\31\1\0\2\31\31\0\6\31\1\174\17\31\1\0"+
    "\2\31\31\0\17\31\1\175\6\31\1\0\2\31\31\0"+
    "\1\31\1\176\24\31\1\0\2\31\4\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4200];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\3\11\1\1\2\11\2\1\4\11"+
    "\3\1\4\11\20\1\2\0\2\11\1\0\4\11\22\1"+
    "\3\0\1\11\1\0\23\1\2\11\43\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    
    private Symbol symbol(int type, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    }
    private Symbol symbol(int type){
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, int yychar1, int yyline1, Object value){
        return new Symbol(type, yyline, yycolumn, value);
    } 
    public int getLine() {
        return yyline+1;
    }

    public int getColumn() {
        return yycolumn+1;
    }       
        


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 130) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 49: 
          { return symbol(sym.RESERVRETURN, yychar, yyline, yytext());
          }
        case 54: break;
        case 9: 
          { return symbol(sym.SIGRESTA, yychar, yyline, yytext());
          }
        case 55: break;
        case 46: 
          { return symbol(sym.LITFALSE, yychar, yyline, yytext());
          }
        case 56: break;
        case 45: 
          { return symbol(sym.RESERVWHILE, yychar, yyline, yytext());
          }
        case 57: break;
        case 5: 
          { return symbol(sym.SEPARADOR, yychar, yyline, yytext());
          }
        case 58: break;
        case 17: 
          { return symbol(sym.SIGMAYOR, yychar, yyline, yytext());
          }
        case 59: break;
        case 34: 
          { return symbol(sym.LITFLOAT, yychar, yyline, yytext());
          }
        case 60: break;
        case 33: 
          { return symbol(sym.TIPOINT, yychar, yyline, yytext());
          }
        case 61: break;
        case 30: 
          { return symbol(sym.SIGMAYORIGUAL, yychar, yyline, yytext());
          }
        case 62: break;
        case 16: 
          { return symbol(sym.SIGMENOR, yychar, yyline, yytext());
          }
        case 63: break;
        case 48: 
          { return symbol(sym.RESERVBREAK, yychar, yyline, yytext());
          }
        case 64: break;
        case 23: 
          { return symbol(sym.LITINT, yychar, yyline, yytext());
          }
        case 65: break;
        case 36: 
          { return symbol(sym.COMENTARIOMULTIPLE, yychar, yyline, yytext());
          }
        case 66: break;
        case 13: 
          { return symbol(sym.SIGCONJUNCION, yychar, yyline, yytext());
          }
        case 67: break;
        case 1: 
          { System.out.println("Error léxico: "+yytext()+" en la línea: "+(yyline+1)+" y columna: "+(yycolumn+1));
          }
        case 68: break;
        case 52: 
          { return symbol(sym.RESERVDEFAULT, yychar, yyline, yytext());
          }
        case 69: break;
        case 24: 
          { /* Ignore */
          }
        case 70: break;
        case 28: 
          { return symbol(sym.SIGDIFERENTE, yychar, yyline, yytext());
          }
        case 71: break;
        case 27: 
          { return symbol(sym.SIGAUMEN, yychar, yyline, yytext());
          }
        case 72: break;
        case 38: 
          { return symbol(sym.RESERVELSE, yychar, yyline, yytext());
          }
        case 73: break;
        case 19: 
          { return symbol(sym.SIGCIERRAPARENT, yychar, yyline, yytext());
          }
        case 74: break;
        case 44: 
          { return symbol(sym.RESERVESCRIBIR, yychar, yyline, yytext());
          }
        case 75: break;
        case 21: 
          { return symbol(sym.SIGCIERRALLAVES, yychar, yyline, yytext());
          }
        case 76: break;
        case 6: 
          { return symbol(sym.SIGNOIGUAL, yychar, yyline, yytext());
          }
        case 77: break;
        case 11: 
          { return symbol(sym.SIGMOD, yychar, yyline, yytext());
          }
        case 78: break;
        case 10: 
          { return symbol(sym.SIGSUMA, yychar, yyline, yytext());
          }
        case 79: break;
        case 32: 
          { return symbol(sym.COMENTARIOSIMPLE, yychar, yyline, yytext());
          }
        case 80: break;
        case 25: 
          { return symbol(sym.IGUAL, yychar, yyline, yytext());
          }
        case 81: break;
        case 14: 
          { return symbol(sym.SIGDISYUNCION, yychar, yyline, yytext());
          }
        case 82: break;
        case 12: 
          { return symbol(sym.SIGPOT, yychar, yyline, yytext());
          }
        case 83: break;
        case 53: 
          { return symbol(sym.RESERVFORRANGE, yychar, yyline, yytext());
          }
        case 84: break;
        case 2: 
          { return symbol(sym.SIGDIV, yychar, yyline, yytext());
          }
        case 85: break;
        case 50: 
          { return symbol(sym.RESERVSWITCH, yychar, yyline, yytext());
          }
        case 86: break;
        case 8: 
          { return symbol(sym.COMA, yychar, yyline, yytext());
          }
        case 87: break;
        case 39: 
          { return symbol(sym.LITTRUE, yychar, yyline, yytext());
          }
        case 88: break;
        case 47: 
          { return symbol(sym.TIPOFLOAT, yychar, yyline, yytext());
          }
        case 89: break;
        case 3: 
          { return symbol(sym.SIGMULTI, yychar, yyline, yytext());
          }
        case 90: break;
        case 18: 
          { return symbol(sym.SIGABREPARENT, yychar, yyline, yytext());
          }
        case 91: break;
        case 37: 
          { return symbol(sym.RESERVLEER, yychar, yyline, yytext());
          }
        case 92: break;
        case 22: 
          { return symbol(sym.IDENTIFICADOR, yychar, yyline, yytext());
          }
        case 93: break;
        case 20: 
          { return symbol(sym.SIGABRELLAVES, yychar, yyline, yytext());
          }
        case 94: break;
        case 29: 
          { return symbol(sym.SIGMENORIGUAL, yychar, yyline, yytext());
          }
        case 95: break;
        case 31: 
          { return symbol(sym.RESERVIF, yychar, yyline, yytext());
          }
        case 96: break;
        case 51: 
          { return symbol(sym.TIPOSTRING, yychar, yyline, yytext());
          }
        case 97: break;
        case 26: 
          { return symbol(sym.SIGDIMINU, yychar, yyline, yytext());
          }
        case 98: break;
        case 15: 
          { return symbol(sym.SIGNEGACION, yychar, yyline, yytext());
          }
        case 99: break;
        case 4: 
          { return symbol(sym.ENDLINE, yychar, yyline, yytext());
          }
        case 100: break;
        case 41: 
          { return symbol(sym.TIPOCHAR, yychar, yyline, yytext());
          }
        case 101: break;
        case 40: 
          { return symbol(sym.RESERVCASE, yychar, yyline, yytext());
          }
        case 102: break;
        case 42: 
          { return symbol(sym.RESERVMAIN, yychar, yyline, yytext());
          }
        case 103: break;
        case 35: 
          { return symbol(sym.LITCHAR, yychar, yyline, yytext());
          }
        case 104: break;
        case 43: 
          { return symbol(sym.TIPOBOOL, yychar, yyline, yytext());
          }
        case 105: break;
        case 7: 
          { return symbol(sym.DOSPUNTOS, yychar, yyline, yytext());
          }
        case 106: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
