
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 27 22:56:06 CST 2023
//----------------------------------------------------

package sintaxis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RESERVFORRANGE = 41;
  public static final int DOSPUNTOS = 4;
  public static final int RESERVCASE = 45;
  public static final int RESERVRETURN = 44;
  public static final int RESERVESCRIBIR = 36;
  public static final int SIGPOT = 12;
  public static final int RESERVBREAK = 43;
  public static final int SIGMULTI = 9;
  public static final int SIGNOIGUAL = 6;
  public static final int LITSTRING = 50;
  public static final int SIGDIMINU = 17;
  public static final int SIGAUMEN = 16;
  public static final int RESERVSWITCH = 39;
  public static final int SIGNEGACION = 15;
  public static final int SEPARADOR = 3;
  public static final int LITFLOAT = 48;
  public static final int RESERVWHILE = 40;
  public static final int TIPOFLOAT = 31;
  public static final int IDENTIFICADOR = 51;
  public static final int RESERVMAIN = 42;
  public static final int IGUAL = 22;
  public static final int SIGCONJUNCION = 13;
  public static final int SIGCIERRALLAVES = 27;
  public static final int ENDLINE = 2;
  public static final int LITFALSE = 29;
  public static final int LITTRUE = 28;
  public static final int SIGDIV = 10;
  public static final int SIGCIERRAPARENT = 25;
  public static final int SIGDISYUNCION = 14;
  public static final int SIGABRELLAVES = 26;
  public static final int EOF = 0;
  public static final int SIGRESTA = 7;
  public static final int TIPOCHAR = 33;
  public static final int SIGDIFERENTE = 23;
  public static final int error = 1;
  public static final int COMA = 5;
  public static final int SIGABREPARENT = 24;
  public static final int RESERVELSE = 38;
  public static final int SIGMOD = 11;
  public static final int TIPOINT = 30;
  public static final int RESERVDEFAULT = 46;
  public static final int RESERVIF = 37;
  public static final int RESERVLEER = 35;
  public static final int TIPOBOOL = 32;
  public static final int SIGMENORIGUAL = 19;
  public static final int TIPOSTRING = 34;
  public static final int COMENTARIOMULTIPLE = 53;
  public static final int SIGSUMA = 8;
  public static final int SIGMENOR = 18;
  public static final int LITINT = 47;
  public static final int COMENTARIOSIMPLE = 52;
  public static final int LITCHAR = 49;
  public static final int SIGMAYOR = 20;
  public static final int SIGMAYORIGUAL = 21;
}

